version: '3'

services:
  
  #Container do Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    networks:
      - rede

  #Container do mysql
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: teste
      MYSQL_ROOT_PASSWORD: teste
    networks:
      - rede

#Rede de comunicação dos containers
networks:
  rede:
    driver: bridge