version: '3'

services:

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    ports:
      - 8080:80
    networks:
      - rede

  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: teste
      MYSQL_ROOT_PASSWORD: teste
    networks:
      - rede


networks:
  rede:
    driver: bridge